-- =====================================================
-- CUSTOMER SHOPPING BEHAVIOR ANALYTICS
-- SQL BUSINESS ANALYSIS
-- =====================================================

-- Database      : MySQL
-- Table         : customer
-- Author        : Devendra Kumar
-- Total Queries : 17
-- =====================================================

/*======================================================
Q1. Revenue by Gender

Objective:
Compare the total revenue generated by male and female
customers to understand gender-wise spending patterns.
======================================================*/

SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;



/*======================================================
Q2. High-Spending Customers Using Discounts

Objective:
Identify customers who used discounts while spending
more than the average purchase amount.
======================================================*/

SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount)
        FROM customer
    )
ORDER BY purchase_amount DESC;



/*======================================================
Q3. Top Rated Products

Objective:
Find the top 5 products having the highest average
customer review ratings.
======================================================*/

SELECT
    item_purchased,
    ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))),2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;



/*======================================================
Q4. Average Purchase Amount by Shipping Type

Objective:
Compare the average purchase amount between
Standard and Express shipping methods.
======================================================*/

SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY average_purchase DESC;



/*======================================================
Q5. Subscription Customer Analysis

Objective:
Compare customer count, average spending, and total
revenue between subscribed and non-subscribed customers.
======================================================*/

SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

/*======================================================
Q6. Products with Highest Discount Usage

Objective:
Identify the products with the highest percentage of
purchases where discounts were applied.
======================================================*/

SELECT
    item_purchased,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;



/*======================================================
Q7. Customer Segmentation

Objective:
Segment customers into New, Returning, and Loyal
based on their previous purchase history.
======================================================*/

WITH customer_type AS
(
    SELECT
        customer_id,
        previous_purchases,

        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment

    FROM customer
)

SELECT
    customer_segment,
    COUNT(*) AS total_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY total_customers DESC;



/*======================================================
Q8. Top 3 Most Purchased Products in Each Category

Objective:
Identify the three most frequently purchased products
within every product category using Window Functions.
======================================================*/

WITH item_counts AS
(
    SELECT

        category,

        item_purchased,

        COUNT(customer_id) AS total_orders,

        ROW_NUMBER() OVER
        (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank

    FROM customer

    GROUP BY
        category,
        item_purchased
)

SELECT
    category,
    item_purchased,
    total_orders,
    item_rank
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;



/*======================================================
Q9. Repeat Buyers vs Subscription Status

Objective:
Analyze whether repeat buyers are more likely to
subscribe compared to occasional customers.
======================================================*/

SELECT

    subscription_status,

    COUNT(customer_id) AS repeat_buyers

FROM customer

WHERE previous_purchases > 5

GROUP BY subscription_status

ORDER BY repeat_buyers DESC;



/*======================================================
Q10. Revenue Contribution by Age Group

Objective:
Determine which age group contributes the highest
overall revenue.
======================================================*/

SELECT

    age_group,

    ROUND(SUM(purchase_amount),2) AS total_revenue

FROM customer

GROUP BY age_group

ORDER BY total_revenue DESC;

/*======================================================
Q11. Revenue by Product Category

Objective:
Analyze revenue generated by each product category
to identify the highest-performing categories.
======================================================*/

SELECT

    category,

    COUNT(*) AS total_orders,

    ROUND(SUM(purchase_amount), 2) AS total_revenue,

    ROUND(AVG(purchase_amount), 2) AS average_purchase

FROM customer

GROUP BY category

ORDER BY total_revenue DESC;



/*======================================================
Q12. Top 10 Customers by Total Spending

Objective:
Identify customers contributing the highest overall
revenue to the business.
======================================================*/

SELECT

    customer_id,

    ROUND(SUM(purchase_amount), 2) AS total_spent,

    COUNT(*) AS total_orders

FROM customer

GROUP BY customer_id

ORDER BY total_spent DESC

LIMIT 10;



/*======================================================
Q13. Most Purchased Products

Objective:
Identify the products purchased most frequently
by customers.
======================================================*/

SELECT

    item_purchased,

    COUNT(*) AS total_orders,

    ROUND(SUM(purchase_amount),2) AS total_revenue

FROM customer

GROUP BY item_purchased

ORDER BY total_orders DESC

LIMIT 10;



/*======================================================
Q14. Average Rating by Product Category

Objective:
Evaluate customer satisfaction across different
product categories using average review ratings.
======================================================*/

SELECT

    category,

    ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))),2) AS average_rating,

    COUNT(*) AS total_reviews

FROM customer

GROUP BY category

ORDER BY average_rating DESC;

/*======================================================
Q15. Revenue Analysis by Payment Method

Objective:
Analyze customer payment preferences by comparing
the number of orders, total revenue, and average
purchase amount for each payment method.
======================================================*/

SELECT

    payment_method,

    COUNT(*) AS total_orders,

    ROUND(SUM(purchase_amount), 2) AS total_revenue,

    ROUND(AVG(purchase_amount), 2) AS average_purchase

FROM customer

GROUP BY payment_method

ORDER BY total_revenue DESC;



/*======================================================
Q16. Seasonal Sales Analysis

Objective:
Identify which season generates the highest revenue
and total customer orders.
======================================================*/

SELECT

    season,

    COUNT(*) AS total_orders,

    ROUND(SUM(purchase_amount), 2) AS total_revenue,

    ROUND(AVG(purchase_amount), 2) AS average_purchase

FROM customer

GROUP BY season

ORDER BY total_revenue DESC;



/*======================================================
Q17. Top 10 Revenue Generating Locations

Objective:
Identify the locations contributing the highest
overall revenue to support regional business strategy.
======================================================*/

SELECT

    location,

    COUNT(*) AS total_orders,

    ROUND(SUM(purchase_amount), 2) AS total_revenue,

    ROUND(AVG(purchase_amount), 2) AS average_purchase

FROM customer

GROUP BY location

ORDER BY total_revenue DESC

LIMIT 10;
